# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :listing do

    factory :non_comic_listing, class: Listing do
      diamd_no "AUG121486"
      stock_no "STK474156"
      parent_item_no_alt ""
      bounce_use_item ""
      full_title "DOCTOR WHO COMPANION CHRON LAST POST AUDIO CD (C: 0-1-2)"
      full_desc "A New Adventure!"
      main_desc "DOCTOR WHO COMPANION CHRON LAST POST AUDIO CD"
      variant_desc ""
      series_code "0"
      issue_no ""
      issue_seq_no "0"
      volume_tag ""
      max_issue ""
      publisher ""
      upc_no ""
      isbn_no nil
      ean_no "978184435949351499"
      cards_per_pack "0"
      pack_per_box "0"
      box_per_case "0"
      discount_code "H"
      increment_no "7"
      prnt_date "8/31/2012"
      foc_vendor "N"
      ship_date "11/28/2012"
      srp "14.99"
      short_isbn_no "1844359492"
      category "16"
      genre "SF"
      brand_code "DW"
      mature "N"
      adult "N"
      oa "N"
      caut1 "0"
      caut2 "1"
      caut3 "2"
      resol "N"
      price "14.99"
      note_price "N"
      order_form_notes ""
      page "377"
      writer "Goss, James"
      artist "Na"
      cover_artist "Holub, Simon"
    end

    factory :issue_listing, class: Listing do
      diamd_no "DEC120650"
      stock_no "STK522777"
      parent_item_no_alt ""
      bounce_use_item ""
      full_title "FANTASTIC FOUR #4 NOW"
      full_desc "The Fantastic four do a thing! "
      main_desc "FANTASTIC FOUR"
      variant_desc "NOW "
      series_code "130857"
      issue_no "4"
      issue_seq_no "1"
      volume_tag ""
      max_issue ""
      publisher "MARVEL COMICS"
      upc_no "75960607906300421"
      isbn_no nil
      ean_no ""
      cards_per_pack "0"
      pack_per_box "0"
      box_per_case "0"
      discount_code "D4"
      increment_no "10"
      prnt_date "1/21/2013"
      foc_vendor "Y"
      ship_date "2/13/2013"
      srp "2.99"
      short_isbn_no ""
      category "1"
      genre "SH"
      brand_code "MH"
      mature "N"
      adult "N"
      oa "N"
      caut1 "0"
      caut2 "0"
      caut3 "0"
      resol "N"
      price "2.99"
      note_price "N"
      order_form_notes "(NOTE: You may order 1 variant for every 50 regular you purchase.)"
      page "36"
      writer "Fraction, Matt"
      artist "Bagley, Mark"
      cover_artist "Bagley, Mark"
    end

    factory :variant_listing, class: Listing do
      diamd_no "DEC120651"
      stock_no "STK523334"
      parent_item_no_alt ""
      bounce_use_item ""
      full_title "FANTASTIC FOUR #4 DODSON VAR NOW"
      full_desc "The Fantastic four do a thing! "
      main_desc "FANTASTIC FOUR"
      variant_desc "DODSON VAR NOW "
      series_code "130857"
      issue_no "4"
      issue_seq_no "1"
      volume_tag ""
      max_issue ""
      publisher "MARVEL COMICS"
      upc_no "75960607906300421"
      isbn_no nil
      ean_no ""
      cards_per_pack "0"
      pack_per_box "0"
      box_per_case "0"
      discount_code "D4"
      increment_no "10"
      prnt_date "1/21/2013"
      foc_vendor "Y"
      ship_date "2/13/2013"
      srp "2.99"
      short_isbn_no ""
      category "1"
      genre "SH"
      brand_code "MH"
      mature "N"
      adult "N"
      oa "N"
      caut1 "0"
      caut2 "0"
      caut3 "0"
      resol "N"
      price "2.99"
      note_price "N"
      order_form_notes "(NOTE: You may order 1 variant for every 50 regular you purchase.)"
      page "36"
      writer "Fraction, Matt"
      artist "Bagley, Mark"
      cover_artist "Dodson, Terry"
    end
  end
end
